services:
  - type: web
    name: pocketbase-minio
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MINIO_ROOT_USER
        sync: false
      - key: MINIO_ROOT_PASSWORD
        sync: false
      - key: MINIO_ENDPOINT
        sync: false
      - key: MINIO_PORT
        value: "9000"
      - key: MINIO_USE_SSL
        value: "true"
      - key: MINIO_BUCKET
        value: "pocketbase-uploads"
    healthCheckPath: /_/
    autoDeploy: true 