services:
  - type: web
    name: minio
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    disk:
      name: data
      mountPath: /data
      sizeGB: 10
    envVars:
      - key: MINIO_ROOT_USER
        sync: false
      - key: MINIO_ROOT_PASSWORD
        sync: false
    ports:
      - port: 9000
        name: minio 