services:
  - type: web
    name: minio
    env: docker
    dockerfilePath: ./Dockerfile.minio
    plan: free
    envVars:
      - key: MINIO_ROOT_USER
        sync: false
      - key: MINIO_ROOT_PASSWORD
        sync: false 