services:
  - type: pserv
    name: minio
    env: docker
    dockerfilePath: ./Dockerfile.minio
    disk:
      name: minio-data
      mountPath: /data
      sizeGB: 10
    envVars:
      - key: MINIO_ROOT_USER
        sync: false
      - key: MINIO_ROOT_PASSWORD
        sync: false 